// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package publicdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID     int32            `json:"order_id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ProductID   int32            `json:"product_id"`
	Quantity    int32            `json:"quantity"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	Status      string           `json:"status"`
	OrderDate   pgtype.Timestamp `json:"order_date"`
}

type Product struct {
	ProductID   int32            `json:"product_id"`
	ProductName string           `json:"product_name"`
	Category    string           `json:"category"`
	Description string           `json:"description"`
	UnitPrice   pgtype.Numeric   `json:"unit_price"`
	ImageUrl    string           `json:"image_url"`
	Stock       int32            `json:"stock"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	UserID      pgtype.UUID      `json:"user_id"`
	Username    string           `json:"username"`
	FullName    string           `json:"full_name"`
	PhoneNumber string           `json:"phone_number"`
	Role        string           `json:"role"`
	Street      string           `json:"street"`
	City        string           `json:"city"`
	PostCode    string           `json:"post_code"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
