// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    product_name, 
    category, 
    description, 
    unit_price, 
    image_url, 
    stock
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING product_id
`

type CreateProductParams struct {
	ProductName string         `json:"product_name"`
	Category    string         `json:"category"`
	Description string         `json:"description"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	ImageUrl    string         `json:"image_url"`
	Stock       int32          `json:"stock"`
}

// Requirement: Mobile app menambah product
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductName,
		arg.Category,
		arg.Description,
		arg.UnitPrice,
		arg.ImageUrl,
		arg.Stock,
	)
	var product_id int32
	err := row.Scan(&product_id)
	return product_id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products 
WHERE product_id = $1
`

// Requirement: Mobile app delete product
func (q *Queries) DeleteProduct(ctx context.Context, productID int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, productID)
	return err
}

const listAllProductsAdmin = `-- name: ListAllProductsAdmin :many
SELECT 
    image_url, 
    product_id, 
    product_name, 
    category, 
    unit_price, 
    stock
FROM products
ORDER BY product_id ASC
`

type ListAllProductsAdminRow struct {
	ImageUrl    string         `json:"image_url"`
	ProductID   int32          `json:"product_id"`
	ProductName string         `json:"product_name"`
	Category    string         `json:"category"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Stock       int32          `json:"stock"`
}

// Requirement: Mobile app fetching data product list
func (q *Queries) ListAllProductsAdmin(ctx context.Context) ([]ListAllProductsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllProductsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProductsAdminRow
	for rows.Next() {
		var i ListAllProductsAdminRow
		if err := rows.Scan(
			&i.ImageUrl,
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.UnitPrice,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products 
SET 
    product_name = $2,
    category = $3,
    description = $4,
    unit_price = $5,
    image_url = $6,
    stock = $7,
    updated_at = NOW()
WHERE product_id = $1
`

type UpdateProductParams struct {
	ProductID   int32          `json:"product_id"`
	ProductName string         `json:"product_name"`
	Category    string         `json:"category"`
	Description string         `json:"description"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	ImageUrl    string         `json:"image_url"`
	Stock       int32          `json:"stock"`
}

// Requirement: Mobile app update product
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ProductID,
		arg.ProductName,
		arg.Category,
		arg.Description,
		arg.UnitPrice,
		arg.ImageUrl,
		arg.Stock,
	)
	return err
}
