// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decreaseProductStock = `-- name: DecreaseProductStock :exec
UPDATE products 
SET stock = stock - $2 
WHERE product_id = $1
`

type DecreaseProductStockParams struct {
	ProductID int32 `json:"product_id"`
	Stock     int32 `json:"stock"`
}

// PENTING: Dipakai Go saat status berubah jadi 'paid'
func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) error {
	_, err := q.db.Exec(ctx, decreaseProductStock, arg.ProductID, arg.Stock)
	return err
}

const getOrderQuantityAndProduct = `-- name: GetOrderQuantityAndProduct :one
SELECT product_id, quantity 
FROM orders 
WHERE order_id = $1
`

type GetOrderQuantityAndProductRow struct {
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

// PENTING: Dipakai Go untuk mengetahui jumlah stok yang harus dikurangi
func (q *Queries) GetOrderQuantityAndProduct(ctx context.Context, orderID int32) (GetOrderQuantityAndProductRow, error) {
	row := q.db.QueryRow(ctx, getOrderQuantityAndProduct, orderID)
	var i GetOrderQuantityAndProductRow
	err := row.Scan(&i.ProductID, &i.Quantity)
	return i, err
}

const listPendingOrders = `-- name: ListPendingOrders :many
SELECT 
    o.order_id,
    o.order_date,
    o.total_amount,
    o.quantity,
    o.status,
    u.full_name AS customer_name,
    u.phone_number,
    p.product_name,
    p.image_url
FROM orders o
JOIN users u ON o.user_id = u.user_id
JOIN products p ON o.product_id = p.product_id
WHERE o.status = 'pending'
ORDER BY o.order_date ASC
`

type ListPendingOrdersRow struct {
	OrderID      int32            `json:"order_id"`
	OrderDate    pgtype.Timestamp `json:"order_date"`
	TotalAmount  pgtype.Numeric   `json:"total_amount"`
	Quantity     int32            `json:"quantity"`
	Status       string           `json:"status"`
	CustomerName string           `json:"customer_name"`
	PhoneNumber  string           `json:"phone_number"`
	ProductName  string           `json:"product_name"`
	ImageUrl     string           `json:"image_url"`
}

func (q *Queries) ListPendingOrders(ctx context.Context) ([]ListPendingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOrdersRow
	for rows.Next() {
		var i ListPendingOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderDate,
			&i.TotalAmount,
			&i.Quantity,
			&i.Status,
			&i.CustomerName,
			&i.PhoneNumber,
			&i.ProductName,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $2 
WHERE order_id = $1
`

type UpdateOrderStatusParams struct {
	OrderID int32  `json:"order_id"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.OrderID, arg.Status)
	return err
}
