// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingOrders = `-- name: ListPendingOrders :many
SELECT 
    o.order_id,
    o.order_date,
    o.total_amount,
    o.quantity,
    o.status,
    -- Ambil info User biar admin tau siapa yang beli
    u.full_name AS customer_name,
    u.phone_number,
    -- Ambil info Product biar admin tau barang apa
    p.product_name,
    p.image_url
FROM orders o
JOIN users u ON o.user_id = u.user_id
JOIN products p ON o.product_id = p.product_id
WHERE o.status = 'pending'
ORDER BY o.order_date ASC
`

type ListPendingOrdersRow struct {
	OrderID      int32            `json:"order_id"`
	OrderDate    pgtype.Timestamp `json:"order_date"`
	TotalAmount  pgtype.Numeric   `json:"total_amount"`
	Quantity     int32            `json:"quantity"`
	Status       string           `json:"status"`
	CustomerName string           `json:"customer_name"`
	PhoneNumber  string           `json:"phone_number"`
	ProductName  string           `json:"product_name"`
	ImageUrl     string           `json:"image_url"`
}

// Requirement: Mobile app fetching data order yang pending
func (q *Queries) ListPendingOrders(ctx context.Context) ([]ListPendingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOrdersRow
	for rows.Next() {
		var i ListPendingOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderDate,
			&i.TotalAmount,
			&i.Quantity,
			&i.Status,
			&i.CustomerName,
			&i.PhoneNumber,
			&i.ProductName,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $2 
WHERE order_id = $1
`

type UpdateOrderStatusParams struct {
	OrderID int32  `json:"order_id"`
	Status  string `json:"status"`
}

// Requirement: Mobile app mengubah data pending menjadi paid atau cancelled
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.OrderID, arg.Status)
	return err
}
