// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storefront.sql

package publicdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductDetail = `-- name: GetProductDetail :one
SELECT 
    product_id,
    image_url, 
    product_name, 
    stock, 
    unit_price, 
    category,
    description
FROM products
WHERE product_id = $1
`

type GetProductDetailRow struct {
	ProductID   int32          `json:"product_id"`
	ImageUrl    string         `json:"image_url"`
	ProductName string         `json:"product_name"`
	Stock       int32          `json:"stock"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Category    string         `json:"category"`
	Description string         `json:"description"`
}

// Requirement: Web fetch detail product
func (q *Queries) GetProductDetail(ctx context.Context, productID int32) (GetProductDetailRow, error) {
	row := q.db.QueryRow(ctx, getProductDetail, productID)
	var i GetProductDetailRow
	err := row.Scan(
		&i.ProductID,
		&i.ImageUrl,
		&i.ProductName,
		&i.Stock,
		&i.UnitPrice,
		&i.Category,
		&i.Description,
	)
	return i, err
}

const listAvailableProducts = `-- name: ListAvailableProducts :many
SELECT 
    product_id,
    image_url, 
    product_name, 
    stock, 
    unit_price, 
    category
FROM products
WHERE stock > 0 -- Hanya tampilkan yang ada stok
ORDER BY created_at DESC
`

type ListAvailableProductsRow struct {
	ProductID   int32          `json:"product_id"`
	ImageUrl    string         `json:"image_url"`
	ProductName string         `json:"product_name"`
	Stock       int32          `json:"stock"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Category    string         `json:"category"`
}

// Requirement: Web fetch data product
func (q *Queries) ListAvailableProducts(ctx context.Context) ([]ListAvailableProductsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableProductsRow
	for rows.Next() {
		var i ListAvailableProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ImageUrl,
			&i.ProductName,
			&i.Stock,
			&i.UnitPrice,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
